#!/bin/csh -f

# @(#)$Header: /afs/isis/depts/cep/emc/apps/archive/filesetapi/filesetapi/sysflags,v 1.4 2004/08/15 20:12:24 cseppan Exp $

#  Determine operating system for compiling SMOKE
source $EDSS_ROOT/scripts/platform

if ( $status != 0 ) then
    exit( $status )
endif

# Make directories for library, object files, and executables
setenv    FS_BIN "$FS_ROOT/$EDSS_EXE"
if( ! -e $FS_BIN ) mkdir -p $FS_BIN

switch ( $EDSS_EXE )
  case IRIXn32f90:
  case IRIX6f90:
  case IRIXn64f90:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw
  case SunOS5f90:
#   NOTE: -Bstatic caused problems with ENVYN (perhaps because not
#         using I/O API compiled with f90 ?)
    setenv FFLAGS   "$FFLAGS -I${IOINC} -M${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -M${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw
case HP_UX11f90:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "+U77 -Wl,-L,${FS_BIN}"
    breaksw
case AIX4n64f90:
case AIX4f90:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN} -lxlsmp"
    breaksw
case Linux2_alpha:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw
case Linux2_x86ifc:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw
case Linux2_x86ifort:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw    
case Linux2_x86pg:
    setenv FFLAGS   "$FFLAGS -I${IOINC} -I${FS_BIN}"
    setenv DBGFLAGS "$DBGFLAGS -I${IOINC} -I${FS_BIN}"
    setenv LDIRS    "-L${FS_BIN}"
    breaksw
default:
    echo "Do not know about executable format "$EDSS_EXE
    exit( 2 )
endsw

