#!/bin/sh
#
. /usrx/local/Modules/default/init/ksh
#
set -xa
export PS4='$SECONDS + '
date -u
############################################
export NET=${NET:-aqm}
export RUN=${RUN:-aqm}
############################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$

# PATH for working directory
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir -p $DATA
cd $DATA
####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=${EXECaqm:-$HOMEaqm/exec}
export FIXaqm=${FIXaqm:-$HOMEaqm/fix}
export USHaqm=${USHaqm:-$HOMEaqm/ush}
export PARMaqm=${PARMaqm:-$HOMEaqm/parm}

###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

# Run setup to initialize working directory and utility scripts

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINnam=${COMINnam:-${COMROOTp1}/nam/prod/nam.${PDY}}
export COMINnamm1=${COMINnamm1:-${COMROOTp1}/nam/prod/nam.${PDYm1}}

mkdir -p $COMOUT

env

###################################################
# Execute the Script
###################################################
${HOMEaqm}/scripts/exaqm_prephyb_nmmb_conus.sh.ecf
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date 

