#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export cmaq_ver=${cmaq_ver:-v6.0.2}
export HOMEaqm=${HOMEaqm:-${PACKAGEROOT}/cmaq.${cmaq_ver}}
export USHaqm=$HOMEaqm/ush
export EXECaqm=$HOMEaqm/exec
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}
# Update the training data period for the PM25 from 1 year (8760) to 3 month (90 day; 2160)
export TMP_STDAY=`${NDATE} -2160 ${PDY}${cyc} | cut -c1-8`  # 1 year 
# The earliest day of training data is August 1 2020
if [ ${TMP_STDAY} -le 20201001 ]; then export TMP_STDAY=20201001; fi
export BC_STDAY=${BC_STDAY:-${TMP_STDAY}}

export Yr=`echo ${PDY} | cut -c1-4`
export Mn=`echo ${PDY} | cut -c5-6`
export Yrmn=`echo ${PDY}  | cut -c1-6`
export Yr1=`echo ${PDYm1} | cut -c1-4`
export Yrmn1=`echo ${PDYm1} | cut -c1-6`
export Yr2=`echo ${PDYm2} | cut -c1-4`
export Yrmn2=`echo ${PDYm2} | cut -c1-6`
export Yr3=`echo ${PDYm3} | cut -c1-4`
export Yrmn3=`echo ${PDYm3} | cut -c1-6`

export ver=${ver:-v6.1}
export COMIN=${COMIN:-${COMROOT}/${NET}/${ver}/${RUN}.${PDY}}
export COMINbicordat=${COMINbicordat:-${COMROOT}/${NET}/${ver}}
export COMINbicor=${COMINbicor:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn}}
export COMINbicorm1=${COMINbicorm1:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn1}}
export COMINbicorm2=${COMINbicorm2:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn2}}
export COMINbicorm3=${COMINbicorm3:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn3}}

export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/prod/dcom}

export COMOUT=${COMOUT:-${COMROOT}/${NET}/${ver}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${ver}/${RUN}.${PDYm1}}
export COMOUTbicor=${COMOUTbicor:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn}}
export COMOUTbicorm1=${COMOUTbicorm1:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn1}}
export COMOUTbicorm2=${COMOUTbicorm2:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn2}}
export COMOUTbicorm3=${COMOUTbicorm3:-${COMROOT}/${NET}/${ver}/bcdata.${Yrmn3}}

if [ -e  $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 ] ; then
 echo "$COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 exists !"
else
 mkdir -p $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008
fi

cp ${DCOMROOT}/${PDYm1}/b008/xx031 $COMINbicorm1/airnow/${Yr1}/${PDYm1}/b008/
cp ${DCOMROOT}/${PDYm2}/b008/xx031 $COMINbicorm2/airnow/${Yr2}/${PDYm2}/b008/
cp ${DCOMROOT}/${PDYm3}/b008/xx031 $COMINbicorm3/airnow/${Yr3}/${PDYm3}/b008/

export PCOM=${PCOM:-${COMOUT}/wmo}

export pgmout=OUTPUT.$$

mkdir -p $COMOUT $PCOM $COMOUTbicorm1 $COMOUTbicorm2 $COMOUTbicorm3

env

export post_proc_hour=${post_proc_hour:-72}

$HOMEaqm/scripts/exaqm_post_pm25_bicor_cs.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job bias correction HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
