#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export USHaqm=$HOMEaqm/ush
export EXECaqm=$HOMEaqm/exec
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

export TMP_STDAY=`${NDATE} -8760 ${PDY}${cyc}`  # 1 year 
export BC_STDAY=`echo $TMP_STDAY | cut -c1-8`

export Yr=`echo ${PDY} | cut -c1-4`
export Mn=`echo ${PDY} | cut -c5-6`
export Yrmn=`echo ${PDY}  | cut -c1-6`
export Yr1=`echo ${PDYm1} | cut -c1-4`
export Yrmn1=`echo ${PDYm1} | cut -c1-6`
export Yr2=`echo ${PDYm2} | cut -c1-4`
export Yrmn2=`echo ${PDYm2} | cut -c1-6`


export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINbicordat=${COMINbicordat:-${COMROOT}/${NET}/${envir}}
export COMINbicor=${COMINbicor:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn}}
export COMINbicorm1=${COMINbicorm1:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn1}}
export COMINbicorm2=${COMINbicorm2:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn2}}

export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMOUTbicor=${COMOUTbicor:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn}}
export COMOUTbicorm1=${COMOUTbicorm1:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn1}}
export COMOUTbicorm2=${COMOUTbicorm2:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn2}}

if [ -e  $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 ] ; then
 echo "$COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 exists !"
else
 mkdir -p $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008
fi

cp -rp ${DCOMROOT}/us007003/${PDYm1}/b008/xx031 $COMINbicorm1/airnow/${Yr1}/${PDYm1}/b008/
cp -rp ${DCOMROOT}/us007003/${PDYm2}/b008/xx031 $COMINbicorm2/airnow/${Yr2}/${PDYm2}/b008/

export PCOM=${PCOM:-${PCOMROOT}/${NET}}

export pgmout=OUTPUT.$$

mkdir -p $COMOUT $PCOM $COMOUTbicorm1 $COMOUTbicorm2

env

$HOMEaqm/scripts/exaqm_post_pm25_bicor_cs.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job bias correction HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
