#!/bin/ksh
#
############################################
# Set up environment for AIR QUALITY PREMAQ 
############################################
set -xa
export PS4='$SECONDS + '
date 

############################################
export NET=aqm
export RUN=HI
############################################

#####################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$

# PATH for working directory

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then
   # NCO
  if [[ ${envir} == prod ]]; then
    TMPhome=/tmpnwprd1
  else
    TMPhome=/tmpnwprd2
  fi
   export DATA=$TMPhome/${job}.${pid}
fi

export DATA=${DATA:-/tmpnwprd2/${job}.${pid}}
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
then
   # NCO
   if [ ${envir} = "prod" ]
   then
     export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
   else
     export jlogfile=/com/logs/${envir}/jlogfile
     #export DBNROOT=/nwprod/spa_util/para_dbn
     export DBNROOT=/nwprod/spa_util/fakedbn
   fi
else
   # DEV
   export jlogfile=/dev/null
fi

##############################
# Define MP variables
##############################
#export MEMORY_AFFINITY=MCM
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
export MP_HOLDTIME=1000

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

export SENDCOM=YES

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=${HOMEaqm}/parm

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
export PARMutil=/nwprod/util/parm

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

export COM=/com/${NET}/${envir}
export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-/com/${NET}/${envir}/${RUN}.${PDYm1}}

export INPEMIDIR=${INPEMIDIR:-/com/${NET}/${envir}/emission}

mkdir -p $COMOUT
 
env
###################################################
# Execute the Script
###################################################
$HOMEaqm/scripts/exaqm_premaq_cb05_hi.sh.ecf
err=$?; err_chk
##################################################
cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"


###################################
# Remove temp directories
###################################

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then  # NCO
  cd $TMPhome
  rm -rf $DATA
else # DEV
  echo "Keeping data directory $DATA"
fi

date

