#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${PACKAGEROOT}/${model}.${version}}
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export NET=${NET:-aqm}
export RUN=${RUN:-HI}

export COMIN=${COMIN:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMINm1=${COMINm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}
export COMINm2=${COMINm2:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm2})}
export COMINm3=${COMINm3:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm3})}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMOUTm1=${COMOUTm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}

## Define Input directories for various information
if [ "${FCST}" = "YES" ] ; then
   COMINmet=${COMIN} #> meteorology input directory
   export YM=`echo ${PDY} | cut -c1-6`
   export MM=`echo ${PDY} | cut -c5-6`
else
   COMINmet=${COMINm1}
   export YM=`echo ${PDYm1} | cut -c1-6`
   export MM=`echo ${PDYm1} | cut -c5-6`
fi
#export COMINemi=${COMINemi:-$COMROOT/$NET/${ver}/emission/${YM}}  #> emissions input directory
export COMINemi=${COMINemi:-$(compath.py -o $NET/${cmaq_ver}/emission/${YM})}  #> emissions input directory
export COMINmet=${COMINmet:-${COMIN}} #> CMAQ processed meteorology directory
export COMINbc=${COMINbc:-${COMINmet}} #> boundary conditions input  directory

mkdir -p ${COMOUT}

export pgmout=OUTPUT.$$

export TYPE_POINT_EMIS_OUT=${TYPE_POINT_EMIS_OUT:-2DSUM}
export TYPE_FIRE_EMIS_OUT=${TYPE_FIRE_EMIS_OUT:-2DSUM}
export FLAG_POINT_EMIS_OUT=${FLAG_POINT_EMIS_OUT:-NO}
export FLAG_3DPOINT_EMIS_OUT=${FLAG_3DPOINT_EMIS_OUT:-NO}
export KEEPDATA=${KEEPDATA:-YES}

env

###################################################
# Execute the Script
###################################################
if [ ! -s ${COMINm1}/aqm.t${cyc}z.fire_emi_HI_r.ncf ] && [ $cyc == '06' ] && [ $FCST = NO ]; then
   echo "No GBBEPx fire emissions for 24-hr reanalysis run at 06z cycle"
else
   startmsg
   ${HOMEaqm}/scripts/exaqm_cmaqv531_hi.sh
   export err=$?; err_chk
fi
##################################################
cat ${pgmout}

msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg   "${msg}"

###################################
# Remove temp directories
###################################
if [ "${KEEPDATA}" != "YES" ] ; then
  cd ${DATAROOT}
  rm -rf ${DATA}
fi

date
