#!/bin/ksh

source /opt/modules/default/init/ksh

set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M
export PS4='$SECONDS + '
date -u

############################################
export NET=${NET:-aqm}
export RUN=${NET:-aqm}
############################################

#####################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

##############################
# Define MP variables
##############################
ulimit -s unlimited
export LANG=en_US
export MP_EAGER_LIMIT=65536
export MP_COREFILE_FORMAT=core.txt
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2
export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
#export MP_USE_BULK_XFER=yes
export MPICH_THROTTLE_ALLTOALL=0

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=${EXECaqm:-$HOMEaqm/exec}
export FIXaqm=${FIXaqm:-$HOMEaqm/fix}
export USHaqm=${USHaqm:-$HOMEaqm/ush}
export PARMaqm=${PARMaqm:-$HOMEaqm/parm}
export UTILaqm=${UTILaqm:-$HOMEaqm/util}

###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

#export utilexec=${utilexec:-$NWROOT/util/exec}
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINm2=${COMINm2:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm2}}
export COMINm3=${COMINm3:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm3}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

export INPEMIDIR=${INPEMIDIR:-${COMROOT}/${NET}/${envir}/emission}

mkdir -p $COMOUT
 
env

###################################################
# Execute the Script
###################################################
${HOMEaqm}/scripts/exaqm_cmaqv502_cs.sh.ecf
export err=$?; err_chk
##################################################
cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

