#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export NET=${NET:-aqm}
export RUN=${RUN:-cs}

export USHaqm=$HOMEaqm/ush
export EXECaqm=$HOMEaqm/exec
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export TMP_STDAY=`${NDATE} -8760 ${PDY}${cyc} | cut -c1-8`  # 1 year back
# The earliest day of training data is August 1 2020
if [ ${TMP_STDAY} -le 20200801 ]; then export TMP_STDAY=20200801; fi
export BC_STDAY=${BC_STDAY:-${TMP_STDAY}}

export Yr=`echo ${PDY} | cut -c1-4`
export Mn=`echo ${PDY} | cut -c5-6`
export Yrmn=`echo ${PDY}  | cut -c1-6`
export Yr1=`echo ${PDYm1} | cut -c1-4`
export Yrmn1=`echo ${PDYm1} | cut -c1-6`
export Yr2=`echo ${PDYm2} | cut -c1-4`
export Yrmn2=`echo ${PDYm2} | cut -c1-6`
export Yr3=`echo ${PDYm3} | cut -c1-4`
export Yrmn3=`echo ${PDYm3} | cut -c1-6`

export COMIN=${COMIN:-$(compath.py ${NET}/${aqm_ver}/${RUN}.${PDY})}
export COMINbicordat=${COMINbicordat:-$(compath.py ${NET}/${aqm_ver})}
export COMINbicor=${COMINbicor:-$(compath.py ${NET}/${aqm_ver}/bcdata.${Yrmn})}
export COMINbicorm1=${COMINbicorm1:-$(compath.py ${NET}/${aqm_ver}/bcdata.${Yrmn1})}
export COMINbicorm2=${COMINbicorm2:-$(compath.py ${NET}/${aqm_ver}/bcdata.${Yrmn2})}
export COMINbicorm3=${COMINbicorm3:-$(compath.py ${NET}/${aqm_ver}/bcdata.${Yrmn3})}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${aqm_ver}/${RUN}.${PDY})}
export COMOUTm1=${COMOUTm1:-$(compath.py -o ${NET}/${aqm_ver}/${RUN}.${PDYm1})}

export COMOUTbicor=${COMOUTbicor:-$(compath.py -o ${NET}/${aqm_ver}/bcdata.${Yrmn})}
export COMOUTbicorm1=${COMOUTbicorm1:-$(compath.py -o ${NET}/${aqm_ver}/bcdata.${Yrmn1})}
export COMOUTbicorm2=${COMOUTbicorm1:-$(compath.py -o ${NET}/${aqm_ver}/bcdata.${Yrmn2})}
export COMOUTbicorm3=${COMOUTbicorm1:-$(compath.py -o ${NET}/${aqm_ver}/bcdata.${Yrmn3})}

export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/prod/dcom}

if [ -e  $COMINbicorm1/airnow/csv/$Yr1/${PDYm1} ] ; then
 echo "$COMINbicorm1/airnow/csv/$Yr1/${PDYm1} exists !"
else
 mkdir -p $COMINbicorm1/airnow/csv/$Yr1/${PDYm1}
fi

cp ${DCOMROOT}/${PDYm1}/airnow/HourlyAQObs_${PDYm1}*.dat $COMINbicorm1/airnow/csv/${Yr1}/${PDYm1}/
cp ${DCOMROOT}/${PDYm2}/airnow/HourlyAQObs_${PDYm2}*.dat $COMINbicorm2/airnow/csv/${Yr2}/${PDYm2}/
cp ${DCOMROOT}/${PDYm3}/airnow/HourlyAQObs_${PDYm3}*.dat $COMINbicorm3/airnow/csv/${Yr3}/${PDYm3}/

export PCOM=${PCOM:-${COMOUT}/wmo}

export pgmout=OUTPUT.$$

mkdir -p $COMOUT $PCOM $COMOUTbicorm1 $COMOUTbicorm2 $COMOUTbicorm3

export KEEPDATA=${KEEPDATA:-YES}

env

export post_proc_hour=${post_proc_hour:-72}

$HOMEaqm/scripts/exaqm_post_o3_bicor_cs.sh
export err=$?; err_chk

cat $pgmout
msg="JOB $job bias correction HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
