#!/bin/ksh

date 
export PS4=' $SECONDS + '
set -x


export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export USHaqm=$HOMEaqm/ush
export EXECaqm=$HOMEaqm/exec
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export COMINfv3=${COMINfv3:-$(compath.py gfs/prod/gfs.$PDY)}
export COMINfv3m1=${COMINfv3m1:-$(compath.py gfs/prod/gfs.$PDYm1)}
export COMIN=${COMIN:-$(compath.py ${NET}/${envir}/$RUN.$PDY)}

export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/$RUN.$PDY}

mkdir -p $COMOUT 

export pgmout=OUTPUT.$$

env

${HOMEaqm}/scripts/exaqm_prephyb_fv3gfs_cs.sh.ecf
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

if [ "${KEEPDATA}" != YES ]; then
  rm -rf $DATA
fi

date

