#!/bin/ksh
source /opt/modules/default/init/ksh
module load iobuf
module load prod_util


date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINm2=${COMINm2:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm2}}
export COMINm3=${COMINm3:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm3}}

export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}

#export PCOM=${PCOM:-${PCOMROOT}/$NET}
export PCOM=${PCOM:-${COMOUT}/wmo}

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

mkdir -p ${COMOUT} ${PCOM}

export pgmout=OUTPUT.$$

env

if [ "${cyc}" != "06" ] && [ "${cyc}" != "12" ]; then
   echo "ERROR WARNING - JAQM_POST1_CS_early only be applied to CMAQ 06z and 12z cycle"
   echo "ERROR WARNING - PROGRAM exit without doing the inter-mediate POST1 processes"
   exit
fi

##  Need to match with soft link runtime file defined in ~/scripts/exaqm_cmaqv531_cs.sh.ecf
file_check=${COMOUT}/aqm.${cycle}.aconc.ncf
let ic=0
let icnt=210
while [ ${ic} -le ${icnt} ]; do
  if [ -s ${file_check} ]; then
     tstep=$(ncdump -h ${file_check} | grep 'TSTEP = UNLIMITED' | sed 's/[^0-9]*//g')
     if [ ${tstep} -ge 48 ]; then
        echo "Current time ${tstep} reach or pass hour 48"
        break
     else
        echo "Waiting FCST hours to reach hour 48 : ${tstep}"
        sleep 20
     fi
  fi
  ((ic++))
done

echo "ic = ${ic}"
if [ ${ic} -gt ${icnt} ]; then
   echo "ERROR WARNING - ${cycle} forecast run has not finished 48 hours in 70 mins"
   echo "ERROR WARNING - JAQM_POST1_CS_early exit without doing the inter-mediate POST1 processes"
   if [ "${KEEPDATA}" != "YES" ] ; then rm -rf ${DATA}; fi
   exit
fi
## Begin stage 1 48 hours output post-processing
export post_proc_hour=${post_proc_hour:-48}

${HOMEaqm}/scripts/exaqm_post1_cb6r3_cs.sh.ecf
export err=$?; err_chk

## if [ ${cyc} -eq 06 -o ${cyc} -eq 12 ] ; then
if [ "${cyc}" == "06" ] || [ "${cyc}" == "12" ]; then
  ${HOMEaqm}/scripts/exaqm_post1_cb6r3_cs.maxi.sh.ecf
  export err=$?; err_chk
fi

if [ -s ${pgmout} ]; then cat ${pgmout}; fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "${jlogfile}" "${msg}"

if [ "${KEEPDATA}" != "YES" ] ; then rm -rf ${DATA}; fi

date
