#!/bin/ksh

export PS4='$SECONDS + '
date
set -xa

####################################
# Specify whether the run is production or development
####################################
export envir=${envir:-prod}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-fv3gfs}

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA=${DATA:-$DATAROOT/${jobid}}
mkdir -p $DATA
cd $DATA
export KEEPDATA=${KEEPDATA:-NO}

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"
export pgmerr=errfile

export ERRSCRIPT=err_chk
export LOGSCRIPT=startmsg
export REDOUT='1>>'
export REDERR='2>'

####################################
# Specify version numbers
####################################
export crtm_ver=${post_crtm_ver:-v2.0.6}
export gfs_ver=${gfs_ver:-v15.0.0}
export hwrf_ver=${hwrf_ver:-v11.0.5}
export g2tmpl_ver=${g2tmpl_ver:-v1.5.0}

###########################################
# Run setpdy and initialize PDY variables
###########################################
export cycle=t${cyc}z
setpdy.sh
. ./PDY

###########################################
# Specify grib version: grib1 or grib2
###########################################
export GRIBVERSION=${GRIBVERSION:-'grib2'}
#export res=${res:-0p25}

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# RERUN    - Rerun posts from beginning (default no)
# VERBOSE  - Specify Verbose Output in global_postgp.sh
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export RERUN=${RERUN:-NO}
export VERBOSE=${VERBOSE:-YES}

####################################
# Specify Execution Areas
####################################
export HOMECRTM=${HOMECRTM:-${NWROOThps}/lib/crtm/${crtm_ver}}
export FIXCRTM=${CRTM_FIX:-${HOMECRTM}/src/fix}
#export FIXCRTM=${FIXCRTM:-${NWROOThps}/hwrf.${hwrf_ver}/fix/hwrf-crtm-2.0.6}
#### export FIXCRTM=${FIXCRTM:-$HOMECRTM/sorc/fix}

export HOMEgfs=${HOMEgfs:-${NWROOT}/gfs.${gfs_ver}}
export EXECgfs=${EXECgfs:-$HOMEgfs/exec}
export FIXgfs=${FIXgfs:-$HOMEgfs/fix}
export USHgfs=${USHgfs:-$HOMEgfs/ush}
export SCRgfs=${SCRgfs:-$HOMEgfs/scripts}
export UTILgfs=${UTILgfs:-$HOMEgfs/util}
export PARMpost=${PARMpost:-$HOMEgfs/parm/post}

##############################
# Set up the UTILITIES
##############################
export SIGHDR=${SIGHDR:-$EXECgfs/global_sighdr}


##############################
# Fields, levels to put in grib file
##############################
export PostFlatFile000=${PostFlatFile000:-${PARMpost}/postxconfig-NT-HYSPLIT-F000.txt}
export PostFlatFile=${PostFlatFile:-${PARMpost}/postxconfig-NT-HYSPLIT.txt}

##############################################
# Define COM directories
##############################################
#export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}}
export COMIN=${COMIN:-$(compath.py ${NET}/${envir}/${RUN}.${PDY})/${cyc}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${envir}/${RUN}.${PDY}/${cyc}}
mkdir -m 775 -p $COMOUT

############################################
# Define location of specific executables
############################################
export POSTGPEXEC=${POSTGPEXEC:-$EXECgfs/gfs_ncep_post}

####################################
# Specify Special Post Vars
####################################
if [ $RUN = gfs ];then
  export FHOUT_PGB=${FHOUT_GFS:-3} #Output frequency of gfs pgb file at 1.0 and 0.5 deg.
fi
if [ $RUN = gdas ]; then
  export IGEN_GFS="gfs_avn"
  export IGEN_ANL="anal_gfs"
  export IGEN_FCST="gfs_avn"
  export IGEN_GDAS_ANL="anal_gdas"
  export FHOUT_PGB=${FHOUT:-1} #Output frequency of gfs pgb file at 1.0 and 0.5 deg.
fi

if [ $GRIBVERSION = grib2 ]; then
  export IGEN_ANL="anal_gfs"
  export IGEN_FCST="gfs_avn"
  export IGEN_GFS="gfs_avn"
fi

#######################################
# Specify Restart File Name to Key Off
#######################################
#restart_file=$COMIN/${RUN}.t${cyc}z.logf
restart_file=$COMIN/${RUN}.t${cyc}z.sfcf

####################################
# Specify Timeout Behavior of Post
#
# SLEEP_TIME - Amount of time to wait for
#              a restart file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for restart files
####################################
export SLEEP_TIME=900
export SLEEP_INT=5

env

if [ "${run84}" = "YES" ]
then
# this section for hours 000 - $FHR_MAX

#########################################################
# Execute the Script
#########################################################
#$SCRgfs/ex${RUN}_nceppost.sh.ecf
$SCRgfs/exaqm_fv3gfs_post.sh.ecf

else
# this section for hours 024 from previous cycle (f006 when cycle is 6-hourly)
#   and global2arl for all fhr's

  ## copy from JHYSPT_PREP_GFS_NCEPPOST
  #export allfhr=024       #006 when 4 cycles a day  # this defined in working run script
   export FHR_START=000
   export ENDHRS=${allfhr}
   export FHR_MAX=084
   ### save values to go back to them for exhysplit_global2arl
   cyc_save=${cyc}
   cycle_save=${cycle}
   PDY_save=${PDY}

   #### now get f06 from previous cycle. Forecast fields such as precip
   ####   and fluxes will be written to the +0 hour of the output file
   ####   written to $COMOUT_HYSPT
   previous=$( ${NDATE} -${allfhr} ${PDY}${cyc} )
   PDYprev=`echo ${previous} | cut -c1-8`
   export PDY=${PDYprev}
   cycprev=`echo ${previous} | cut -c9-10`
   export cyc=${cycprev}
   export cycle=t${cyc}z
   ## NOT used export GESdir=${GESdirprev:-$gespath/${RUN}.${PDY}}
   #export COMIN=${COMINprev:-${COMROOT}/${NET}/prod/${RUN}.${PDY}}
   ## what is syntax so this has a default??
   export COMMDLIN=${COMMDLINROOT}/${RUN}.${PDYprev}

  #export COMIN=${DATA}   # 3-27-18 barbara comment out and add line below
   export COMIN=${COMMDLIN}
  #export COMIN=${COMIN:-$(compath.py ${NET}/${envir}/${RUN}.${PDY})/${cyc}} ## from above

   # create a dummy logf file (for this f006 file from previous cycle
  #cp ${COMMDLIN}/${RUN}.t${cyc}z.atmf${post_times}.nemsio ${COMIN}/${RUN}.t${cyc}z.logf${post_times}
  #export restart_file=${COMIN}/${RUN}.t${cyc}z.logf

  ## get input files in proper names for POST
  #cp ${COMMDLIN}/${RUN}.t${cyc}z.atmf${post_times}.nemsio ${COMIN}/${RUN}.t${cyc}z.sf${post_times}
  #cp ${COMMDLIN}/${RUN}.t${cyc}z.flxf${post_times}.nemsio ${COMIN}/${RUN}.t${cyc}z.sfluxgrbf${post_times}
  #export NEMSINP=${COMIN}/${RUN}.t${cyc}z.sf${post_times}
  #export FLXINP=${COMIN}/${RUN}.t${cyc}z.sfluxgrbf${post_times}

   typeset -Z3 post_times ENDHR INCR

   export post_times=${post_times:-"${allfhr}"}
   export ENDHRS=${ENDHRS:-$allfhr}
   export INCR=${INCR:-003}

   while [ $post_times -le $ENDHRS ];do
      echo "post_times: ${post_times}"
      export post_times
      export SHOUR=192
      export FHOUR=204
      export FHINC=12
      export HDMAX=36
     ####################################
      # Specify Timeout Behavior of Post
      #
      # SLEEP_TIME - Amount of time to wait for
      #              a restart file before exiting
      # SLEEP_INT  - Amount of time to wait between
      #              checking for restart files
      ####################################
      export SLEEP_TIME=900
      export SLEEP_INT=5

      #############################################################
      # Execute the script
      #/nw${envir}/scripts/exglobal_post_gfs.sh.sms
      # use own post control file and executable
      date

     #${HOMEhysplit}/scripts/exhysplit_prep_gfs_nceppost_latlon.sh.ecf
      $SCRgfs/ex${RUN}_nceppost.sh.ecf
      export err=$?; err_chk

      date

    # copy master file from subdirectory it was created in to main directory $DATA
     #cp -p gfs.t${cyc}z.master.grb2f${post_times} ${DATAorg}
      ((post_times=post_times+INCR))
      if [ $post_times -lt 100 ];then post_times="0"${post_times};fi
   done

   ### go back to previous values
   cyc=${cyc_save}
   cycle=${cycle_save}
   PDY=${PDY_save}

   # RESET DATA here, cd to regular DATA, the top layer of runtime directory
   export DATA=${DATAorg}
   cd ${DATA}

   export PDYprev
   export cycprev

   #############################################################
   # Execute the script to convert master files to HYSPLIT-format
   #############################################################
#  ${SCRgfs}/exhysplit_prep_gfs_nceppost_global2arl.sh.ecf
   export err=$?; err_chk
   echo $?
   ######################################################################
   # Remove the Temporary working directory, recall DATA is now DATAorg (as command above)
   ######################################################################
   if [ "$KEEPDATA" != "YES" ] ; then
      cd $DATAROOT
      rm -rf $DATA
   fi

   date -u
  ## end copy from JHYSPT_PREP_GFS_NCEPPOST
fi

##############################
# Remove the Temporary working directory
##############################
#cd $DATAROOT
#if [ $KEEPDATA = NO ]; then
#  rm -rf $DATA
#fi

date
