#!/bin/sh

############################################
# Set up environment for AIR QUALITY CMAQ(FCST)
############################################
set -xa
export MP_IOAGENT_CNT=all
export MP_IO_BUFFER_SIZE=8M
export PS4='$SECONDS + '
date -u

############################################
export NET=aqm
export RUN=AK
############################################
############################################
export PARAFLAG=${PARAFLAG:-NO}
#####################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$
export job=aqm_fcst_cs
export DATA=${DATA:-/tmpnwprd/${job}.${pid}}
mkdir -p $DATA
cd $DATA 

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.$$}
####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

#export MP_HOLDTIME=1000
export MP_LABELIO=YES

export cycle=t${cyc}z
export SENDCOM=YES
export SENDDBN=NO
export SENDECF=YES

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=$HOMEaqm/parm
export UTILaqm=$HOMEaqm/util

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec


# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
sh $utilscript/postmsg.sh "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

export COM=/com/${NET}/${envir}
export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-/com/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINm2=${COMINm2:-/com/${NET}/${envir}/${RUN}.${PDYm2}}
export COMINm3=${COMINm3:-/com/${NET}/${envir}/${RUN}.${PDYm3}}

export INPEMIDIR=${INPEMIDIR:-/com/aqm/prod/emission}

mkdir -p $COMOUT
 
env
###################################################
# Execute the Script
###################################################
${HOMEaqm}/scripts/exaqm_cmaqv46_ak.sh.ecf
err=$?; err_chk
##################################################
cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#cd /tmpnwprd
#rm -rf $DATA

date

