#!/bin/ksh 
#
. /usrx/local/Modules/default/init/ksh

set -xa
export PS4='$SECONDS + '
date -u 

############################################
export NET=${NET:-aqm}
export RUN=${RUN:-aqm}
############################################
# obtain unique process id (pid) and make temp directories
############################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}

export DATA=${DATA:-${DATAROOT:-/${job}.${pid}}}

mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=${HOMEaqm}/parm
export USHaqm=${HOMEaqm}/ush
###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

DAYOFYEAR=`$NWROOTp1/util/ush/date2jday.sh $PDY`

#-----------------------------------------------------------------
# Maxinum layer for smoke
#-----------------------------------------------------------------
export SMKLAY=35  #22
#-----------------------------------------------------------------
#  critical value for eliminating short life Fire
#-----------------------------------------------------------------
export XSFIRE=2400           # 24 hours
#------------------------------------------------------------------
#  temporary store BLUESKY HYSPLIT
#------------------------------------------------------------------
# FIRE EMISSION OUTPUT
#------------------------------------------------------------------
export FEMS=$DATA/scenario/$PDY
#------------------------------------------------------------------

export smoke_emis=${smoke_emis:-${COMROOTp1}/hysplit/prod}

export FEMIT=${smoke_emis}/smoke.$PDY/EMITIMES

if [ ${cyc} = '00' -o ${cyc} = '18' ]
then
  nstep=7
else
  nstep=49
fi
#------------------------
#
export PDY=${PDY:-}
YY=`echo $PDY | cut -c 1-4`
MM=`echo $PDY | cut -c 5-6`
DD=`echo $PDY | cut -c 7-8`
jj=`/bin/date --date=$YY'/'$MM'/'$DD +%j`
typeset -Z3 jj       # set Julian day to be 3 digit, ex. 023, 345..
today=${YY}${jj}
#-----------------------------------------------------------------
# get yesterday's date & Julian
#-----------------------------------------------------------------
YYm1=`echo $PDYm1 | cut -c 1-4`
MMm1=`echo $PDYm1 | cut -c 5-6`
DDm1=`echo $PDYm1 | cut -c 7-8`
jjm1=`/bin/date --date=$YYm1'/'$MMm1'/'$DDm1 +%j`
typeset -Z3 jjm1     # set Julian day to be 3 digit, ex. 023, 345..
yesterday=${YYm1}${jjm1}
#----------------------------------------------------------
#---    DIR OF LOG FILES AND SMALL OUTPUTS -----------------
#-----------------------------------------------------------
 export LOGD=$DATA/logs
 export LOG1=$DATA/logs/Bluesky-A
 export LOG2=$DATA/logs/STEP2-A
 export LSMK=$DATA/logs/SMKINV-A
 export LOG3=$DATA/logs/STEP3-A

# export METDIR=/ptmpp1/$LOGNAME/tmp/aqm.$PDY
#=============================================
 export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
 export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
 export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

 mkdir -p $COMOUT

#############################################
###  NGAC output dir 
 export NGAC_DIR=${NGAC_DIR:-${COMROOTp1}/ngac/prod}
###############################################
# Set up the daily emission files directory
# Those are fix files but use huge disk space.
###############################################
export INPEMIDIR=${INPEMIDIR:-/com2/${NET}/${envir}/emission}

env

###################################################
# Execute the Script
###################################################
ksh $HOMEaqm/scripts/exaqm_premaq_cb05_cs.sh.ecf
err=$?; err_chk
##################################################
cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

