#!/bin/ksh
#

source /opt/modules/default/init/ksh

############################################
# Set up environment for AQM PREGEN 
############################################
set -xa
export PS4='$SECONDS + '
date -u

############################################
export NET=aqm
export RUN=aqm
############################################

############################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$

# PATH for working directory

#if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
#then
#   # NCO
#  if [[ ${envir} == prod ]]; then
#    TMPhome=/tmpnwprd1
#  else
#    TMPhome=/tmpnwprd2
#  fi
#   export DATA=$TMPhome/${job}.${pid}
#fi

export DATA=${DATA:-/tmpnwprd2/${job}.${pid}}
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
#if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
#then
#   # NCO
#   if [ ${envir} = "prod" ]
#   then
#     export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
#   else
#     export jlogfile=/com/logs/${envir}/jlogfile
#     #export DBNROOT=/nwprod/spa_util/para_dbn
#     export DBNROOT=/nwprod/spa_util/fakedbn
#   fi
#else
#   # DEV
#   export jlogfile=/dev/null
#fi

export jlogfile=${jlogfile:-${usr_tmp}/com/logs/jlogfiles/jlogfile.${job}.${pid}}

##############################
# Define MP variables
##############################
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
export MP_HOLDTIME=1000

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

export SENDCOM=YES
export DONAM12=YES
export DONESTS=NO

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export USHaqm=$HOMEaqm/ush
export PARMaqm=$HOMEaqm/parm
export UTILaqm=$HOMEaqm/util

export USHnam=/gpfs/td1/emc/meso/save/Eric.Rogers/nam.v4.0.0/ush
export PARMnam=/gpfs/td1/emc/meso/save/Eric.Rogers/nam.v4.0.0/parm

###################################
# Set up the UTILITIES
###################################
module load prod_util
#export utilscript=/gpfs/hps/emc/naqfc/noscrub/arl.aqm/cmaq5.0.2/util
#export utilexec=/gpfs/hps/emc/naqfc/noscrub/arl.aqm/cmaq5.0.2/util

# Run setup to initialize working directory and utility scripts
#sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

#$utilscript/setpdy.sh
setpdy.sh
. PDY

export COM=/com/${NET}/${envir}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMNMM=${COMNMM:-/com/nam/prod/nam.${PDY}}
export COMNMMm1=${COMNMMm1:-/com/nam/prod/nam.${PDYm1}}

mkdir -p $COMOUT

env

###################################################
# Execute the Script
###################################################
${HOMEaqm}/scripts/exaqm_prephyb_nmmb_conus.sh.ecf
err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################

#if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
#then  # NCO
#  cd $TMPhome
#  rm -rf $DATA
#else # DEV
#  echo "Keeping data directory $DATA"
#fi

date -u

