#!/bin/sh

set -xa
export PS4='$SECONDS + '
date -u

############################################
export NET=${NET:-aqm}
export RUN=${RUN:-HI}
############################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}

export DATA=${DATA:-${DATAROOT}/${jobid}}

mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}
export SENDECF==${SENDECF:-YES}

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=$HOMEaqm/parm
export USHaqm=$HOMEaqm/ush

####################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

# Run setup to initialize working directory and utility scripts

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

export pcom=${pcom:-${PCOMROOT}/${NET}}

mkdir -p $COMOUT $pcom

env

###################################################
# Execute Script aqm_post
###################################################
$HOMEaqm/scripts/exaqm_post2_cb05_hi.sh.ecf
err=$?; err_chk

cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
