#!/bin/sh
#
. /usrx/local/Modules/default/init/ksh
#
set -xa
export PS4='$SECONDS + '
date -u
############################################
# Set up environment for AQM PREGEN 
############################################
export RUN_ENVIR=${RUN_ENVIR:-nco}
export COMROOT=${COMROOT:-/com2}
export NWROOT=${NWROOT:-/nw${envir}2}
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export KEEPDATA${KEEPDATA:-NO}
###########################################
export NET=${NET:-aqm}
export RUN=${RUN:-HI}
############################################
# obtain unique process id (pid) 
# and make temp directories
############################################
export pid=$$

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
mkdir -p $DATA
cd $DATA
####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export USHaqm=$HOMEaqm/ush
export PARMaqm=$HOMEaqm/parm
###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

###########################################
# Run setpdy and initialize PDY variables
###########################################
#sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMNMM=${COMNMM:-${COMROOT}/nam/prod/nam.${PDY}}
export COMNMMm1=${COMNMMm1:-${COMROOT}/nam/prod/nam.${PDYm1}}

mkdir -p $COMOUT

env

###################################################
# Execute the Script
###################################################
${HOMEaqm}/scripts/exaqm_prephyb_nmmb_hi.sh.ecf
err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi
date

