#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${PACKAGEROOT}/${model}.${version}}
export USHaqm=$HOMEaqm/ush
export EXECaqm=$HOMEaqm/exec
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export RUN=${RUN:-AK}

export COMIN=${COMIN:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMINm1=${COMINm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}
export COMINm2=${COMINm2:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm2})}
export COMINm3=${COMINm3:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm3})}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMOUTm1=${COMOUTm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}

mkdir -p $COMOUT

export pgmout=OUTPUT.$$

export KEEPDATA=${KEEPDATA:-YES}

env

$HOMEaqm/scripts/exaqm_post3_cb6r3_ak.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
