#!/bin/ksh
#
#. /usrx/local/Modules/default/init/ksh

set -xa
export PS4='$SECONDS + '
date -u

#####################################
export pid=$$

# PATH for working directory

#export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

############################################
# Set up environment for AIR QUALITY FCST
############################################
export NET=aqm
export RUN=emission
export cyc=12
export cycle=t12z

#  Default is NO: output to HPSS. YES: output to TSM
export TSM_FLAG=NO

if [ $envir = prod ]; then
  export HPSSOUT=${HPSSOUT:-/NCEPPROD/hpssprod/runhistory}
  export HPSSOUT_OBS=${HPSSOUT_OBS:-/NCEPOBSERV/hpssprod/runhistory}
  export TSMOUT=${TSMOUT:-/hsmprod/runhistory}
else
  export HPSSOUT=${HPSSOUT:-/NCEPPROD/hpsspara/runhistory}
  export HPSSOUT_OBS=${HPSSOUT_OBS:-/NCEPOBSERV/hpsspara/runhistory}
  export TSMOUT=${TSMOUT:-/hsmpara/runhistory}
fi


####################################
# Export variable for TSM write
####################################
export SCP=/opt/freeware/bin/scp
export SCP_CONFIG='-oNoneEnabled=yes -oNoneSwitch=yes -F /home/nwprod/.ossh/ssh_config'

# Define Temporary Directory for writing of HTAR file
#export TMPDIR=$DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export HOMErhist=${HOMErhist:-${HOMEcmaq}}
export USHrhist=${USHrhist:-$HOMErhist/ush}
export PARMrhist=${PARMrhist:-$HOMErhist/parm}

export RUN_DAY=${RUN_DAY:-16}

export INPEMIDIR=${INPEMIDIR:-${COMROOT}/${NET}/${aqm_ver}/emission}

env

#############################################################
# get the current day
#############################################################
current_day=`date +%d`
echo " the current day= $current_day"

#############################################################
# execute the script
if (( ${current_day} == ${RUN_DAY} ))
then
    ${HOMErhist}/scripts/exaqm_emission_archive.sh
fi
#############################################################
if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
