#!/bin/ksh

source /opt/modules/default/init/ksh
module load prod_util

date
export PS4=' $SECONDS + '
set -x


export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec

export USHaqm=$HOMEaqm/ush
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}


export DAYOFYEAR=`date2jday.sh $PDY`
export SMKLAY=35 
export XSFIRE=2400           # 24 hours

#
#export PDY=${PDY:-}
#YY=`echo $PDY | cut -c 1-4`
#MM=`echo $PDY | cut -c 5-6`
#DD=`echo $PDY | cut -c 7-8`
#jj=`/bin/date --date=$YY'/'$MM'/'$DD +%j`
#typeset -Z3 jj       # set Julian day to be 3 digit, ex. 023, 345..
#today=${YY}${jj}
#export today=`date2jday.sh $PDY`
#-----------------------------------------------------------------
# get yesterday's date & Julian
#-----------------------------------------------------------------
#YYm1=`echo $PDYm1 | cut -c 1-4`
#MMm1=`echo $PDYm1 | cut -c 5-6`
#DDm1=`echo $PDYm1 | cut -c 7-8`
#jjm1=`/bin/date --date=$YYm1'/'$MMm1'/'$DDm1 +%j`
#typeset -Z3 jjm1     # set Julian day to be 3 digit, ex. 023, 345..
#yesterday=${YYm1}${jjm1}
#export yesterday=`date2jday.sh $PDYm1`
#----------------------------------------------------------
#---    DIR OF LOG FILES AND SMALL OUTPUTS -----------------
#-----------------------------------------------------------

#export METDIR=/gpfs/hps/ptmp/$LOGNAME/tmp/aqm.$PDY

export COMIN=${COMIN:-$COMROOT/$NET/$envir/$RUN.$PDY}
export COMINm1=${COMINm1:-$COMROOT/$NET/$envir/$RUN.$PDYm1}

export COMOUT=${COMOUT:-$COMROOT/$NET/$envir/$RUN.$PDY}
export COMOUTm1=${COMOUTm1:-$COMROOT/$NET/$envir/$RUN.$PDYm1}

export NGAC_DIR=${NGAC_DIR:-$COMROOTp1/ngac/prod}
export INPEMIDIR=${INPEMIDIR:-$COMROOT/$NET/prod/emission}
export smoke_emis=${smoke_emis:-$COMROOTp2/hysplit/prod}

#export HYPTMP=${DATA}
#export FEMS=$DATA/scenario/$PDY
#export FEMIT=${smoke_emis}/smokecs.$PDY/EMITIMES

#export LOGD=$DATA/logs
#export LOG1=$DATA/logs/Bluesky-A
#export LOG2=$DATA/logs/STEP2-A
#export LSMK=$DATA/logs/SMKINV-A
#export LOG3=$DATA/logs/STEP3-A

mkdir -p $COMOUT

export pgmout=OUTPUT.$$
 
env

if [ "${FCST}" = "YES" ]; then
# $HOMEaqm/scripts/exaqm_premaq_cb05_cs.sh.ecf.new
 $HOMEaqm/scripts/exaqm_premaq_cb05_cs.sh.ecf
  export  err=$?; err_chk
 if [ $cycle = "t06z" ] ; then
  $USHaqm/aqm_ngac_conus_L35_dust.sh $PDY
  err=$?; err_chk
 fi
fi

echo "Good 1"

if [ $cycle = "t06z" ] && [ "${FCST}" = "NO" ] ; then
 $USHaqm/aqm_smoke2cmaq_L35_anal.sh $PDY
 export err=$?; err_chk
fi

echo "Good 2"

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#cd  /tmpnwprd
#rm -rf $DATA

date

