#!/bin/ksh

date
export PS4=' $SECONDS + '
set -x


export DATA=${DATA:-${DATAROOT:?}/$jobid}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=$HOMEaqm/exec

export USHaqm=$HOMEaqm/ush
export PARMaqm=$HOMEaqm/parm
export FIXaqm=$HOMEaqm/fix
export UTILaqm=$HOMEaqm/util

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}


export DAYOFYEAR=`date2jday.sh $PDY`
export SMKLAY=35 
export XSFIRE=2400           # 24 hours

export COMIN=${COMIN:-$COMROOT/$NET/$envir/$RUN.$PDY}
export COMINm1=${COMINm1:-$COMROOT/$NET/$envir/$RUN.$PDYm1}

export COMOUT=${COMOUT:-$COMROOT/$NET/$envir/$RUN.$PDY}
export COMOUTm1=${COMOUTm1:-$COMROOT/$NET/$envir/$RUN.$PDYm1}

export NGAC_DIR=${NGAC_DIR:-$COMROOTp2/ngac/prod}
export INPEMIDIR=${INPEMIDIR:-$COMROOT/$NET/${envir}/emission}
#XXW export smoke_emis=${smoke_emis:-$COMROOTp2/hysplit/${envir}}
export smoke_emis=${smoke_emis:-$COMROOTp2/hysplit4cmaq/${envir}}

mkdir -p $COMOUT

export pgmout=OUTPUT.$$
 
env

if [ "${FCST}" = "YES" ]; then
aprun -n 1 $HOMEaqm/scripts/exaqm_premaq_cb05_ak.sh.ecf
  export  err=$?; err_chk
# if [ $cycle = "t06z" ] ; then
## if [ $cycle = "t12z" ] ; then 
##  aprun -n 1 $USHaqm/aqm_ngac_conus_L35_dust.sh $PDY
##  err=$?; err_chk
## fi
fi

#if [ $cycle = "t06z" ] && [ "${FCST}" = "NO" ] ; then
##if [ $cycle = "t12z" ] && [ "${FCST}" = "NO" ] ; then
## aprun -n 1 $USHaqm/aqm_smoke2cmaq_L35_anal.sh $PDY
## export err=$?; err_chk
##fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "${KEEPDATA}" != YES ]; then
  rm -rf $DATA
fi

date

