#!/bin/sh -x 

date

export PS4=' $SECONDS + '

set -ax

export DATA=${DATA:-${DATAROOT}/${PBS_JOBNAME}.${PBS_JOBID}}

mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${PACKAGEROOT}/${model}.${version}}
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

SYYYY=`echo ${PDY} |cut -c1-4`
SMM=`echo ${PDY} |cut -c5-6`
SDD=`echo ${PDY} |cut -c7-8`
export DAYOFYEAR=`date -d ${SYYYY}/${SMM}/${SDD} +%j`

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export COMIN=${COMIN:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMINm1=${COMINm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDY})}
export COMOUTm1=${COMOUTm1:-$(compath.py -o ${NET}/${cmaq_ver}/${RUN}.${PDYm1})}

export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver}/gfs.${PDY}/${cyc}/atmos)}
export COMINgfsm1=${COMINgfsm1:-$(compath.py gfs/${gfs_ver}/gfs.${PDYm1}/${cyc}/atmos)}

export COMINgefs=${COMINgefs:-$(compath.py gefs/${gefs_ver}/gefs.${PDY})}
export COMINgefsm1=${COMINgefsm1:-$(compath.py gefs/${gefs_ver}/gefs.${PDYm1})}

export LBC_INI=${LBC_INI:-0}     
export LBC_END=${LBC_END:-120}  
export LBC_FREQ=${LBC_FREQ:-3} 

export COMINfire=${COMINfire:-${DCOMROOT}/${PDY}/firewx}
export COMINfirem1=${COMINfirem1:-${DCOMROOT}/${PDYm1}/firewx}

export FLAG_TODAY_FIRE=${FLAG_TODAY_FIRE:-NO}

export COMINgvf=${COMINgvf:-${DCOMROOT}/viirs}
export GVF_FHR=${GVF_FHR:-GVF-WKL-GLB_v2r3_j01}      ## use j01 data first
export GVF_FHR_2=${GVF_FHR_2:-GVF-WKL-GLB_v2r3_npp}  ## use npp as 2nd choice

export KEEPDATA=${KEEPDATA:-YES}

mkdir -p ${COMOUT}

export pgmout=OUTPUT.$$
 
env

if [ "${FCST}" == "YES" ]; then
   export YM=`echo ${PDY} | cut -c1-6`
   export COMINemi=${COMINemi:-$COMROOT/$NET/${ver}/emission/${YM}}  #> emissions input directory

  ${HOMEaqm}/scripts/exaqm_metprep.sh
   export  err=$?; err_chk

   startmsg
   mpiexec -n 1 ${USHaqm}/aqm_gbbepx2pts.ksh 
   export err=$?; err_chk

   if [ "${cycle}" == "t06z" ] || [ "${cycle}" == "t12z" ] ; then
    sh  ${USHaqm}/aqm_fv3chem_L35.sh ${PDY}
      err=$?; err_chk
   fi
elif [ "${FCST}" == "NO" ]; then

   if [ -s ${COMINm1}/aqm.${cycle}.metcro3d.ncf ]; then
      if [ "${cycle}" == "t06z" ]; then   
         startmsg
         mpiexec -n 1 ${USHaqm}/aqm_gbbepx2pts.ksh 
         export err=$?; err_chk
      fi
   else
      echo "WARNING :: ===================================================================="
      echo "WARNING :: aqm.${cycle}.metcro3d.ncf can not be found for Analysis Forecast Run"
      echo "WARNING :: ${cycle} MET_PREP for analysis run will exit normally"
      echo "WARNING :: It is possible that no Meteorology is available at ${cycle} yesterady."
      echo "WARNING :: ===================================================================="
   fi
fi

msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ -e "${pgmout}" ]; then
   cat ${pgmout}
fi

if [ "${KEEPDATA}" != "YES" ]; then
   rm -rf ${DATA}
fi

date
