#!/bin/ksh
#
############################################
# Set up environment for AIR QUALITY PREMAQ 
############################################
set -xa
export PS4='$SECONDS + '
date 

############################################
export NET=aqm
export RUN=AK
############################################
############################################
export PARAFLAG=${PARAFLAG:-NO}
#####################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$
export job=aqm_premaq_ak
export DATA=${DATA:-/tmpnwprd/${job}.${pid}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${pid}}
####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z
export MP_HOLDTIME=1000
export MP_LABELIO=YES

export SENDCOM=YES
export SENDDBN=YES
export SENDECF=YES

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=${HOMEaqm}/parm

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec
export PARMutil=/nwprod/util/parm

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

if [ $PARAFLAG = "YES" ]
then
export SENDDBN=NO
fi

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

 export COM=/com/${NET}/prod
 export COMIN=${COMIN:-/com/${NET}/prod/${RUN}.${PDY}}
 export COMOUT=${COMOUT:-com/${NET}/${envir}/${RUN}.${PDY}}
 export COMNAM=${COMNAM:-/com/${NET}/prod/${RUN}.${PDY}}
 export COMINm1=${COMINm1:-/com/${NET}/prod/${RUN}.${PDYm1}}

export INPEMIDIR=${INPEMIDIR:-/com/${NET}/prod/emission}

mkdir -p $COMOUT
 
env
###################################################
# Execute the Script
###################################################
$HOMEaqm/scripts/exaqm_premaq_cb05_ak.sh.ecf
err=$?; err_chk
##################################################
cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#cd  /tmpnwprd
#rm -rf $DATA

date

