#!/bin/ksh

. /usrx/local/Modules/default/init/ksh

module unload NetCDF/3.6.3
module load NetCDF/4.2/serial
module load HDF5/1.8.9/serial

set -xa
export PS4='$SECONDS + '
date -u

############################################
export NET=${NET:-aqm}
export RUN=${NET:-aqm}
############################################

#####################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}

export DATA=${DATA:-${DATAROOT}/${job}.${pid}}

mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=${EXECaqm:-$HOMEaqm/exec}
export FIXaqm=${FIXaqm:-$HOMEaqm/fix}
export USHaqm=${USHaqm:-$HOMEaqm/ush}
export PARMaqm=${PARMaqm:-$HOMEaqm/parm}

###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

# Run setup to initialize working directory and utility scripts
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

#-------------------------------------------------------------
# create an initial date for Bias Correction training (4 weeks) 
export TMP_STDAY=`${NDATE} -672 ${PDY}${cyc}`
export BC_STDAY=`echo $TMP_STDAY | cut -c1-8`
export Yr4w=`echo ${BC_STDAY} | cut -c1-4`
export Yrmn4w=`echo ${BC_STDAY} | cut -c1-6`

export Yr=`echo ${PDY} | cut -c1-4`
export Mn=`echo ${PDY} | cut -c5-6`
export Yrmn=`echo ${PDY}  | cut -c1-6`
export Yr1=`echo ${PDYm1} | cut -c1-4`
export Yrmn1=`echo ${PDYm1} | cut -c1-6`
export Mnm1=`echo ${PDYm1}  | cut -c5-6`

#-------------------------------------------------------------
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINbicor=${COMINbicor:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn}}
export COMINbicorm1=${COMINbicorm1:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn1}}
export COMINbicor4w=${COMINbicor4w:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn4w}}

#export BICOR_DATA=${BICOR_DATA:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn}}
#export BICOR_DATA1=${BICOR_DATA1:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn1}}
#export BICOR_DATA4w=${BICOR_DATA4w:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn4w}}

#if [ -e  $BICOR_DATA1/airnow/$Yr1/${PDYm1}/b008 ] ; then 
# echo "$BICOR_DATA1/airnow/$Yr1/${PDYm1}/b008 exists !"
#else
# mkdir -p $BICOR_DATA1/airnow/$Yr1/${PDYm1}/b008
#fi

#cp -rp ${DCOMROOT}/us007003/${PDYm1}/b008/xx031 $BICOR_DATA1/airnow/${Yr1}/${PDYm1}/b008/

if [ -e  $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 ] ; then
 echo "$COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 exists !"
else
 mkdir -p $COMINbicorm1/airnow//$Yr1/${PDYm1}/b008
fi

cp -rp ${DCOMROOT}/us007003/${PDYm1}/b008/xx031 $COMINbicorm1/airnow/${Yr1}/${PDYm1}/b008/

pcom=${pcom:-${PCOMROOT}/${envir}/${NET}}

mkdir -p $COMOUT $pcom

env
###################################################
# Execute Script aqm_post
###################################################
$HOMEaqm/scripts/exaqm_post_pm25_bicor_cs.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job bias correction HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

##################################################
# Remove temp directories
##################################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi


date
