#!/bin/ksh


date
export PS4=' $SECONDS + '
set -x

export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p ${DATA}
cd ${DATA}

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. PDY

export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export USHaqm=${USHaqm:-${HOMEaqm}/ush}
export EXECaqm=${EXECaqm:-${HOMEaqm}/exec}
export PARMaqm=${PARMaqm:-${HOMEaqm}/parm}
export FIXaqm=${FIXaqm:-${HOMEaqm}/fix}
export UTILaqm=${UTILaqm:-${HOMEaqm}/util}

export NET=${NET:-aqm}
export RUN=${RUN:-aqm}

export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINm2=${COMINm2:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm2}}
export COMINm3=${COMINm3:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm3}}

export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}

## Define Input directories for various information
if [ "${FCST}" = "YES" ] ; then
   METpath=${COMIN} #> meteorology input directory
   export YM=`echo ${PDY} | cut -c1-6`
   export MM=`echo ${PDY} | cut -c5-6`
else
   METpath=${COMINm1}
   export YM=`echo ${PDYm1} | cut -c1-6`
   export MM=`echo ${PDYm1} | cut -c5-6`
fi
export EMISpath=${EMISpath:-/gpfs/hps/nco/ops/com/aqm/${envir}/emission/${YM}}  #> emissions input directory
export METpath=${METpath:-${COMIN}} #> CMAQ processed meteorology directory
export BCpath=${BCpath:-${METpath}} #> boundary conditions input  directory

export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

mkdir -p ${COMOUT}

export pgmout=OUTPUT.$$

export TYPE_POINT_EMIS_OUT=${TYPE_POINT_EMIS_OUT:-2DSUM}
export TYPE_FIRE_EMIS_OUT=${TYPE_FIRE_EMIS_OUT:-2DSUM}
export FLAG_POINT_EMIS_OUT=${FLAG_POINT_EMIS_OUT:-NO}
export FLAG_3DPOINT_EMIS_OUT=${FLAG_3DPOINT_EMIS_OUT:-NO}
export KEEPDATA=${KEEPDATA:-YES}
export SINGLECYC=${SINGLECYC:-NO}

env

###################################################
# Execute the Script
###################################################
FLAG_RUN_FCST=YES
if [ "${FCST}" == "NO" ]; then
   ##
   ## This is a precaution check in case no ${cycle} meteorology of yesterday is found for analysis run.
   ## It may happen if new implementation was started at 12Z the previous day and analysis run is called for 06Z.
   ## Let the jobs complete successfully and move on to today ${cycle} run without 24-hour backward analysis run.
   ## 
   if [ ! -s ${COMINm1}/aqm.${cycle}.metcro3d.ncf ]; then
      echo "WARNING :: ===================================================================="
      echo "WARNING :: aqm.${cycle}.metcro3d.ncf can not be found for Analysis Forecast Run"
      echo "WARNING :: ${cycle} Analysis Forecast Run will exit normally"
      echo "WARNING :: It is possible that no Meteorology is available at ${cycle} yesterady."
      echo "WARNING :: ===================================================================="
      FLAG_RUN_FCST=NO
   fi
   if [ ! -s ${COMINm1}/aqm.t${cyc}z.fire_emi_cs_r.ncf ] && [ "${cyc}" == "06" ]; then
      echo "WARNING :: ===================================================================="
      echo "WARNING :: ${COMINm1}/aqm.t${cyc}z.fire_emi_cs_r.ncf can not be found for Analysis Forecast Run"
      echo "WARNING :: It is possible that no GBBEPx fire emissions is available at ${cycle} yesterady."
      echo "WARNING :: ===================================================================="
      FLAG_RUN_FCST=NO
   fi
fi
if [ "${FLAG_RUN_FCST}" == "YES" ]; then
   startmsg
   ${HOMEaqm}/scripts/exaqm_cmaqv531_cs.sh.ecf
   export err=$?; err_chk
fi
##################################################
if [ -e "${pgmout}" ]; then
   cat ${pgmout}
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "${jlogfile}" "${msg}"

###################################
# Remove temp directories
###################################
if [ "${KEEPDATA}" != "YES" ] ; then
  rm -rf ${DATA}
fi

date
