#!/bin/ksh
#
set -xa
export PS4='$SECONDS + '
date -u 

############################################
export NET=aqm
export RUN=aqm
############################################

#####################################
# obtain unique process id (pid) and make temp directories
#####################################
export pid=$$

# PATH for working directory

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then
   # NCO
  if [[ ${envir} == prod ]]; then
    TMPhome=/tmpnwprd1
  else
    TMPhome=/tmpnwprd2
  fi
   export DATA=$TMPhome/${job}.${pid}
fi

export DATA=${DATA:-/tmpnwprd2/${job}.${pid}}
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
then
   # NCO
   if [ ${envir} = "prod" ]
   then
     export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
   else
     export jlogfile=/com/logs/${envir}/jlogfile
     #export DBNROOT=/nwprod/spa_util/para_dbn
     export DBNROOT=/nwprod/spa_util/fakedbn
   fi
else
   # DEV
   export jlogfile=/dev/null
fi

##############################
# Define MP variables
##############################
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
#export MP_TASK_AFFINITY=core
#export MP_HOLDTIME=1000

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

export SENDCOM=YES

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=${HOMEaqm}/parm
export USHaqm=${HOMEaqm}/ush
export PARMutil=$HOMEaqm/util/parm

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

DAYOFYEAR=`$HOMEaqm/util/date2jday.sh $PDY`

#-----------------------------------------------------------------
# Maxinum layer for smoke
#-----------------------------------------------------------------
export SMKLAY=35 #22
#-----------------------------------------------------------------
#  critical value for eliminating short life Fire
#-----------------------------------------------------------------
export XSFIRE=2400           # 24 hours
#------------------------------------------------------------------
#  temporary store BLUESKY HYSPLIT
#------------------------------------------------------------------
# export HYPTMP=${usr_tmp}/aqf_nmm_t/rerun_CONUS_fire-COx3_L22_XS
export HYPTMP=${DATA}
#------------------------------------------------------------------
# FIRE EMISSION OUTPUT
#------------------------------------------------------------------
export FEMS=$HYPTMP/scenario/$PDY
#------------------------------------------------------------------

export smoke_emis=${smoke_emis:-/com/hysplit/prod}

export FEMIT=${smoke_emis}/smoke.$PDY/EMITIMES

if [ ${cyc} = '00' -o ${cyc} = '18' ]
then
  nstep=7
else
  nstep=49
fi
#------------------------
#
export PDY=${PDY:-}
YY=`echo $PDY | cut -c 1-4`
MM=`echo $PDY | cut -c 5-6`
DD=`echo $PDY | cut -c 7-8`
jj=`/bin/date --date=$YY'/'$MM'/'$DD +%j`
typeset -Z3 jj       # set Julian day to be 3 digit, ex. 023, 345..
today=${YY}${jj}
#-----------------------------------------------------------------
# get yesterday's date & Julian
#-----------------------------------------------------------------
YYm1=`echo $PDYm1 | cut -c 1-4`
MMm1=`echo $PDYm1 | cut -c 5-6`
DDm1=`echo $PDYm1 | cut -c 7-8`
jjm1=`/bin/date --date=$YYm1'/'$MMm1'/'$DDm1 +%j`
typeset -Z3 jjm1     # set Julian day to be 3 digit, ex. 023, 345..
yesterday=${YYm1}${jjm1}
#----------------------------------------------------------
#---    DIR OF LOG FILES AND SMALL OUTPUTS -----------------
#-----------------------------------------------------------
 export LOGD=$HYPTMP/logs
 export LOG1=$HYPTMP/logs/Bluesky-A
 export LOG2=$HYPTMP/logs/STEP2-A
 export LSMK=$HYPTMP/logs/SMKINV-A
 export LOG3=$HYPTMP/logs/STEP3-A

 export METDIR=/ptmpp1/$LOGNAME/tmp/aqm.$PDY
#=============================================
 export COM=/com/${NET}/${envir}
 export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
 export COMINm1=${COMINm1:-/com/${NET}/${envir}/${RUN}.${PDYm1}}
 export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}

###############################################
# Set up the daily emission files directory
# Those are fix files but use huge disk space.
###############################################
export INPEMIDIR=${INPEMIDIR:-/com/${NET}/${envir}/emission}

export smoke_emis=${smoke_emis:-/com/hysplit/prod}

mkdir -p $COMOUT
 
env

###################################################
# Execute the Script
###################################################
ksh $HOMEaqm/scripts/exaqm_premaq_cb05_cs.sh.ecf
err=$?; err_chk
$USHaqm/aqm_premaq_cb05_winddust_snowcover_hms_emission_cs.sh
err=$?; err_chk
$USHaqm/aqm_gocart_bnd_5x_L35_dust.sh $PDY
err=$?; err_chk
##################################################
cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"


###################################
# Remove temp directories
###################################

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then  # NCO
  cd $TMPhome
  rm -rf $DATA
else # DEV
  echo "Keeping data directory $DATA"
fi

date

