#!/bin/ksh

#. /usrx/local/Modules/default/init/ksh
source /opt/modules/default/init/ksh

module load prod_util

#module unload NetCDF/3.6.3
#module load NetCDF/4.2/serial
#module load HDF5/1.8.9/serial

set -xa
export PS4='$SECONDS + '
date -u

############################################
export NET=${NET:-aqm}
export RUN=${NET:-aqm}
############################################

#####################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=${EXECaqm:-$HOMEaqm/exec}
export FIXaqm=${FIXaqm:-$HOMEaqm/fix}
export USHaqm=${USHaqm:-$HOMEaqm/ush}
export PARMaqm=${PARMaqm:-$HOMEaqm/parm}

###################################
# Set up the UTILITIES
###################################
#module load prod_util
#module load grib_util

# Run setup to initialize working directory and utility scripts
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

#-------------------------------------------------------------
# create an initial date for Bias Correction training (4 weeks) 
export TMP_STDAY=`${NDATE} -8760 ${PDY}${cyc}`  # 1 year 
export BC_STDAY=`echo $TMP_STDAY | cut -c1-8`

export Yr=`echo ${PDY} | cut -c1-4`
export Mn=`echo ${PDY} | cut -c5-6`
export Yrmn=`echo ${PDY}  | cut -c1-6`
export Yr1=`echo ${PDYm1} | cut -c1-4`
export Yrmn1=`echo ${PDYm1} | cut -c1-6`
export Yr2=`echo ${PDYm2} | cut -c1-4`
export Yrmn2=`echo ${PDYm2} | cut -c1-6`

#-------------------------------------------------------------
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMOUTm1=${COMOUTm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMINbicordat=${COMINbicordat:-${COMROOT}/${NET}/${envir}}
export COMINbicor=${COMINbicor:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn}}
export COMINbicorm1=${COMINbicorm1:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn1}}
export COMINbicorm2=${COMINbicorm2:-${COMROOT}/${NET}/${envir}/bcdata.${Yrmn2}}

if [ -e  $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 ] ; then
 echo "$COMINbicorm1/airnow/$Yr1/${PDYm1}/b008 exists !"
else
 mkdir -p $COMINbicorm1/airnow/$Yr1/${PDYm1}/b008
fi

cp -rp ${DCOMROOT}/us007003/${PDYm1}/b008/xx031 $COMINbicorm1/airnow/${Yr1}/${PDYm1}/b008/
cp -rp ${DCOMROOT}/us007003/${PDYm2}/b008/xx031 $COMINbicorm2/airnow/${Yr2}/${PDYm2}/b008/

pcom=${pcom:-${PCOMROOT}/${envir}/${NET}}

mkdir -p $COMOUT $pcom

env
###################################################
# Execute Script aqm_post
###################################################
#$HOMEaqm/scripts/exaqm_post_pm25_bicor_cs.sh.ecf
$HOMEaqm/scripts/exaqm_post_pm25_bicor_cs_omp.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job bias correction HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

##################################################
# Remove temp directories
##################################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
