#!/bin/ksh
#
. /usrx/local/Modules/default/init/ksh

set -xa
export PS4='$SECONDS + '
date -u

############################################
export NET=${NET:-aqm}
export RUN=${RUN:-AK}

############################################
export pid=$$

# PATH for working directory

export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${job}.${pid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export EXECaqm=${EXECaqm:-$HOMEaqm/exec}
export FIXaqm=${FIXaqm:-$HOMEaqm/fix}
export USHaqm=${USHaqm:-$HOMEaqm/ush}
export PARMaqm=${PARMaqm:-$HOMEaqm/parm}

###################################
# Set up the UTILITIES
###################################
module load prod_util
module load grib_util

# Run setup to initialize working directory and utility scripts
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${NET}/${envir}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}

export INPEMIDIR=${INPEMIDIR:-${COMROOT}/${NET}/${envir}/emission}

export pcom=${pcom:-${PCOMROOT}/${NET}}

mkdir -p $COMOUT $pcom

env

###################################################
# Execute Script aqm_post
###################################################
$HOMEaqm/scripts/exaqm_post3_cb05_ak.sh.ecf
export err=$?; err_chk

cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
