#!/bin/ksh

set -xa
export PS4='$SECONDS + '
date -u

############################################
# Set up environment for AIR QUALITY FCST
############################################
export NET=aqm
export RUN=aqm
############################################

#####################################
export pid=$$

# PATH for working directory

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then
   # NCO
  if [[ ${envir} == prod ]]; then
    TMPhome=/tmpnwprd1
  else
    TMPhome=/tmpnwprd2
  fi
   export DATA=$TMPhome/${job}.${pid}
fi

export DATA=${DATA:-/tmpnwprd2/${job}.${pid}}
mkdir -p $DATA

cd $DATA

####################################
# File To Log Msgs
####################################
if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
then
   # NCO
   export SENDCOM=YES
   export SENDDBN=YES
   export SENDDBN_NTC=YES
   export SENDECF=YES

   if [ ${envir} = "prod" ]
   then
     export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.${pid}}
   else
     export jlogfile=/com/logs/${envir}/jlogfile
     export DBNROOT=/nwprod/spa_util/para_dbn
     #export DBNROOT=/nwprod/spa_util/fakedbn
   fi
else
   # DEV
   export SENDCOM=YES
   export SENDDBN=NO
   export SENDDBN_NTC=NO
   export SENDECF=NO
   export jlogfile=/dev/null
fi

##############################
# Define MP variables
##############################
ulimit -s unlimited
export LANG=en_US
export MP_EAGER_LIMIT=65536
export MP_COREFILE_FORMAT=core.txt
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2
export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
export MPICH_THROTTLE_ALLTOALL=0
export MP_HOLDTIME=1000

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

####################################
# Path to HOME Directory
####################################

export HOMEaqm=${HOMEaqm:-/nw${envir}/cmaq.${model_ver}}
export EXECaqm=$HOMEaqm/exec
export FIXaqm=$HOMEaqm/fix
export PARMaqm=$HOMEaqm/parm
export USHaqm=$HOMEaqm/ush
export PARMutil=$HOMEaqm/util/parm

###################################
# Set up the UTILITIES
###################################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
$utilscript/setpdy.sh
. PDY

export COMIN=${COMIN:-/com/${NET}/${envir}/${RUN}.${PDY}}
export COMOUT=${COMOUT:-/com/${NET}/${envir}/${RUN}.${PDY}}

if [ "${envir}" = 'prod' ] || [ "${envir}" = 'para' ] || [ "${envir}" = 'test' ]
then
   # NCO
   if [ ${envir} = "prod" ]
   then
     export pcom=${pcom:-/pcom/${NET}}
   else
     export pcom=${pcom:-/pcom/${envir}/${NET}}
   fi
fi

mkdir -p $COMOUT $pcom
env

###################################################
# Execute Script aqm_post
###################################################
$HOMEaqm/scripts/exaqm_post3_cb05_cs.sh.ecf
err=$?; err_chk

cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################

if [ "$envir" = 'prod' ] || [ "$envir" = 'para' ] || [ "$envir" = 'test' ]
then  # NCO
  cd $TMPhome
  rm -rf $DATA
else # DEV
  echo "Keeping data directory $DATA"
fi

date
