#!/bin/ksh
#
. $MODULESHOME/init/ksh

set -xa
export PS4='$SECONDS + '
date -u

############################################
# Set up environment for AIR QUALITY FCST
############################################
export NET=aqm
export RUN=aqm
############################################

export sendmail='Y'

#####################################
# PATH for working directory
#test='Y'
#if [ $test = 'Y' ];then
#DATAROOT=/gpfs/hps3/ptmp/$USER
#DATA=$DATAROOT/tmp.1
#DCOMIN=$DATAROOT/dcom
##COMOUT=$DATAROOT/com
#COMOUThps=$DATAROOT/com
#HOMEaqm=/gpfs/hps3/emc/naqfc/noscrub/Youhua.Tang/nwprod-2018
#RUN_DAY=24
#module load prod_util
#fi

export DATAROOT=${DATAROOT:-/gpfs/hps/nco/ops/tmpnwprd}
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${COMROOT}/logs/jlogfiles/jlogfile.${jobid}}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

export cycle=${cycle:-t${cyc}z}

export SENDCOM=${SENDCOM:-YES}

####################################
# Path to HOME Directory
####################################
export HOMEaqm=${HOMEaqm:-${NWROOT}/cmaq.${cmaq_ver}}
export USHaqm=${USHaqm:-$HOMEaqm/ush}

###################################
# Set up the UTILITIES
###################################
#module load prod_util
#module load grib_util

# Run setup to initialize working directory and utility scripts
msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

# Run setpdy and initialize PDY variables
export cycle=t12z
setpdy.sh
. PDY

#XXW export RUN_DAY=${RUN_DAY:-16}
export RUN_DAY=${RUN_DAY:-29}

export DCOMIN=${DCOMIN:-${DCOMROOT}/us007003/aqm_emission/${envir}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/emission}
export COMOUThps=${COMOUThps:-/gpfs/hps/nco/ops/com/${NET}/${envir}/emission}
env

#############################################################
# get the current day
##############################################################
current_day=`date +%d`
echo " the current day= $current_day"

#############################################################
# execute the script
#############################################################
if (( ${current_day} == ${RUN_DAY} ))
then
   $HOMEaqm/scripts/exaqm_emission_ingest.sh.ecf
fi

#cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

###################################
# Remove temp directories
###################################
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
