#!/bin/ksh
#
#BSUB -oo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_pregen_hi.out
#BSUB -eo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_pregen_hi.out
#BSUB -J jcmaq_pregen_hi
#BSUB -n 4
##BSUB -q dev2 
#BSUB -q dev2
#BSUB -P CMAQ-T2O
#BSUB -x
#BSUB -R span[ptile=1]
##BSUB -R "affinity[core]"
#BSUB -W 00:30
##BSUB -R "rusage[mem=3000]"
#BSUB -a poe
##

#export MP_SHARED_MEMORY=yes
#export MEMORY_AFFINITY=MCM
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
export MP_TASK_AFFINITY=core
export MP_HOLDTIME=1000

# for EMC test
export RUN_ENVIR=notnco
export COMROOT=/ptmpp2/${USER}/com2
export NWROOT=/naqfc/save/${USER}/nwdev
export cmaq_ver=v4.6.6
export envir=para1
export job=aqm_prephy_hi
#

# EXPORT list here
set -ax
#export envir=para
export PARAFLAG=YES
export SENDCOM=YES
export SENDDBN=NO
export SENDECF=NO

 
${HOMEaqm}/jobs/JAQM_PREPHYB_HI

err=$?
if [ "${PARAFLAG}" = "YES" ]
then
 #err=$?
  if [ ${err} -ne 0 ]
  then
    exit 249
  fi
fi



