#!/bin/ksh
#
#BSUB -oo /ptmpp2/Jianping.Huang/com/output/para1/today/jaqm_premaq_cs.out
#BSUB -eo /ptmpp2/Jianping.Huang/com/output/para1/today/jaqm_premaq_cs.out
#BSUB -J jaqm_premaq_cs_v465
#BSUB -n 1 
#BSUB -x
#BSUB -R span[ptile=1]
#BSUB -W 01:29
#BSUB -q dev2
##BSUB -q dev2
#BSUB -R "rusage[mem=10000]"
#BSUB -P CMAQ-T2O
#BSUB -a poe
##BSUB -a openmpi
##

#export MP_SHARED_MEMORY=yes
#export MEMORY_AFFINITY=MCM
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
export MP_TASK_AFFINITY=core
#

# EXPORT list here
set -ax
#export envir=para
export PARAFLAG=YES
 
${HOMEaqm}/jobs/JAQM_PREMAQ_CS

err=$?
if [ "${PARAFLAG}" = "YES" ]
then
 #err=$?
  if [ ${err} -ne 0 ]
  then
    exit 249
  fi
fi



