#!/bin/ksh
#
#BSUB -oo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_fcst_ak.out
#BSUB -eo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_fcst_ak.out 
#BSUB -J jaqm_fcst_v466_ak
#BSUB -n 64 
#BSUB -x
#BSUB -R span[ptile=16]
#BSUB -W 00:50
##BSUB -q dev2
#BSUB -q dev2
#BSUB -P CMAQ-T2O 
##BSUB -R "rusage[mem=1500]"
#BSUB -a poe

#module load ics
#module load ibmpe

ulimit -s unlimited

export LANG=en_US
export MP_EAGER_LIMIT=65536
export MP_COREFILE_FORMAT=core.txt
export MP_EUIDEVELOP=min
export MP_EUIDEVICE=sn_all
export MP_EUILIB=us
export MP_MPILIB=mpich2

export MP_LABELIO=yes
export MP_SINGLE_THREAD=yes
export MP_TASK_AFFINITY=cpu
#export MP_USE_BULK_XFER=yes
export MPICH_THROTTLE_ALLTOALL=0


# EXPORT list here
set -ax

# for EMC test
export RUN_ENVIR=notnco
export COMROOT=/ptmpp2/${USER}/com2
export NWROOT=/naqfc/save/${USER}/nwdev
export cmaq_ver=v4.6.6
export envir=para1
export job=aqm_cmaq_ak
#
export PARAFLAG=YES

export SENDCOM=YES
export SENDDBN=NO
export SENDECF=NO

${HOMEaqm}/jobs/JAQM_FORECAST_AK

err=$?
if [ "${PARAFLAG}" = "YES" ]
then
 #err=$?
  if [ ${err} -ne 0 ]
  then
    exit 249
  fi
fi



