#!/bin/ksh
#
#BSUB -oo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_premaq_ak.out
#BSUB -eo /ptmpp2/Jianping.Huang/com2/output/para1/today/jaqm_premaq_ak.out
#BSUB -J jaqm_premaq_ak
#BSUB -n 1 
#BSUB -x
#BSUB -R span[ptile=1]
#BSUB -W 01:50
##BSUB -q dev2 
#BSUB -q dev2
#BSUB -P CMAQ-T2O 
##BSUB -a poe
##BSUB -a openmpi
##

#export MP_SHARED_MEMORY=yes
#export MEMORY_AFFINITY=MCM
export MP_EUILIB=us
export MP_EUIDEVICE=sn_all
export MP_MPILIB=mpich2
export MP_STDOUTMODE=unordered
export MP_LABELIO=yes
export MP_TASK_AFFINITY=core
#

# EXPORT list here
set -ax

export RUN_ENVIR=notnco
#export COMROOT=/ptmpp2/${USER}/com2
#export NWROOT=/naqfc/save/${USER}/nwdev
export cmaq_ver=v4.6.6
export envir=para1
export job=aqm_premaq_ak

export PARAFLAG=YES

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=NO
export SENDECF=NO

${HOMEaqm}/jobs/JAQM_PREMAQ_AK

err=$?
if [ "${PARAFLAG}" = "YES" ]
then
 #err=$?
  if [ ${err} -ne 0 ]
  then
    exit 249
  fi
fi



